title: Shark attacks visualization with AWS & Toucan
description: "This a fictional web site created with the AWS blog post to showcase what you can achieve when combining Redshift Serverless and Toucan"
google_analytics:

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
